[project]
name = "empowerk12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "ipython>=9.10.0",
    "nbformat>=5.10.4",
    "pandas>=3.0.0",
    "prefect>=3.6.15",
    "ruff>=0.14.14",
]
